name: Developement

on:

  workflow_dispatch:

jobs:
  tests:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@7
        with:
          node-version: "24"